name: Build TensorFlow Lite for MACOS

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout TensorFlow
        uses: actions/checkout@v4
        with:
          repository: tensorflow/tensorflow
          ref: v2.18.0

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install -U six numpy wheel packaging

      - name: Configure TensorFlow
        run: |
          export TF_NEED_ROCM=0
          export TF_NEED_CUDA=0
          python configure.py

      - name: Build TensorFlow Lite C
        run: bazel build -c opt  //tensorflow/lite:libtensorflowlite.dylib

      - name: Zip and Upload Artifact
        run: |
          mkdir -p output
          zip -r output/TensorFlowLite_macos.zip bazel-bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TensorFlowLite_macos.zip
          path: output/*.zip
